### ISSUE TITLE
[Send App]: 

### ISSUE THREAD

**Issue by lizardwine** [blazap/blazap-db#3]
### App Name

VScode

### Category

Text Editors

### App Description

Visual Studio Code, also commonly referred to as VS Code. is a source code editor made by Microsoft with Electron framework
for Windows, Linux and macOS Features include support for syntax highlighting, intelligent code completion, snippets, code refactoring, and embedded Git. 
Users can change the theme, keyboard shortcuts, preferences, and install extensions that add additional functionality.

### Website URL

https://code.visualstudio.com/

### Developer

Microsoft

**Comment by itroeix** [comment]
App Added
ID: 4
App Name: VS Code
Description: Visual Studio Code, also commonly referred to as VS Code. is a source code editor made by Microsoft with Electron framework for Windows, Linux and macOS.
Developer: Microsoft
Shared: lizardwine
